name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build image
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push image
        run: bash build.sh
        shell: bash